#!/bin/bash

shopt -s nullglob

newFormat="pdf"

allFiles=$(find . -name '*.svg')

echo $allFiles

for f in $allFiles
do
	echo "Processing $f"
    filename="${f%.*}"
    newName="$filename.$newFormat"
    echo "Exporting to $newName"
    /Applications/Inkscape.app/Contents/Resources/bin/inkscape --export-background-opacity=0 --export-pdf=$newName $f
done
