#!/bin/bash

# the prefix used for the new files
prefix="pdf/"
# the extension for the new files
suffix=".pdf"

echo

# --porcelain allows for high compatibility between git versions
# -uno switch stands for -u[no], means don't show unstaged files
git status --porcelain -uno | while IFS= read -r line; do
# get the full file paths
    f=${line#???}
# loop over svg files
    case ${f} in *.svg)
        echo "Processing $f"
        fileName=${f#*/}

# create any missing directories, otherwise the inkscape export will fail
        dirs=$(dirname $fileName)
        dirs=$prefix$dirs
        mkdir -p $dirs

# build new file path from the prefix and suffix
        fileName=${fileName%.svg}
        fileName=$prefix$fileName$suffix
        echo "Exporting to $fileName"
        /Applications/Inkscape.app/Contents/Resources/bin/inkscape --export-background-opacity=0 --export-pdf=$fileName $f >&/dev/null

# add file to this commit
        echo "Adding $fileName to index"
        git add $fileName

        echo
    esac
done