#!/bin/bash

echo "pre-commit hook start"

# the directory we are interested in
dirPrefix="product/assets"
# svg directory name
svgName="svg"
# the replacement for the svg directory
replacementName="pdf"
# the extension for the new files
suffix=".pdf"

echo

# --porcelain allows for high compatibility between git versions
# -uno switch stands for -u[no], means don't show unstaged files
git status --porcelain -uno | while IFS= read -r line; do
# get the full file paths
    f=${line#???}
# loop over svg files, but we are only interested in the ones in the dirPrefix, and they need to be in the "svg" folder
    if [[ ${f} == $dirPrefix* && ${f} == */$svgName/*.svg ]] ; then

        echo "Processing $f"
        fileName=${f##*/}

# create any missing directories, otherwise the inkscape export will fail
        dirs=$(dirname $f)
        dirs=$(dirname $dirs)/$replacementName
        mkdir -p $dirs

# build new file path from the processed directory, fileName and suffix
        fileName=${fileName%.svg}
        newFilePath=$dirs/$fileName$suffix

# we need to detect if the file is being deleted, if yes, clean up the pdf too
        status=${line:0:3}
        echo status = $status
        if [ ${status} == D ] ; then
            if [ -f $newFilePath ] ; then
                echo -n "Deleting $newFilePath ... "
                rm $newFilePath
                echo "Done"
                echo "Adding deletion to index"
                git add --all $newFilePath
            else
                echo "Tried to delete $newFilePath but it doesn't exist"
            fi
            continue
        fi

# if the file is not being deleted, we can create the pdf
        echo "Exporting to $newFilePath"
        /Applications/Inkscape.app/Contents/Resources/bin/inkscape --export-background-opacity=0 --export-pdf=$newFilePath $f >&/dev/null

# add file to this commit
        echo "Adding $newFilePath to index"
        git add $newFilePath

        echo
    fi
done

echo "pre-commit hook end"